# Generated by Django 3.2.16 on 2023-02-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.IntegerField(choices=[(3, 'Client'), (2, 'Employee'), (1, 'Manager')], default=3),
        ),
    ]
