# Generated by Django 3.2.16 on 2023-02-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='feedback',
            field=models.TextField(blank=True, default='No feedback given so far.', max_length=200),
        ),
    ]
