# Generated by Django 3.2.16 on 2023-02-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='client',
            new_name='user',
        ),
    ]
