# Generated by Django 3.2.16 on 2023-01-24 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': [('is_manager', 'Is manager'), ('is_employee', 'Is employee'), ('is_client', 'Is client')]},
        ),
    ]
