# Generated by Django 3.2.16 on 2023-02-16 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_dashboard', '0002_alter_job_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=200, validators=[django.core.validators.RegexValidator('^\\d*[a-zA-Z][a-zA-Z0-9]*$')]),
        ),
    ]
