# Generated by Django 3.2.16 on 2023-02-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_dashboard', '0003_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
